# Generated by Django 4.2.11 on 2024-03-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('menu_category_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'menu Category',
                'verbose_name_plural': 'menu Categories',
                'ordering': ['menu_category_order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menucategory')),
            ],
            options={
                'ordering': ['menu_order'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_selection', models.CharField(choices=[('standard', 'Standard'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical')], max_length=20)),
                ('block_position', models.CharField(max_length=50)),
                ('row', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('show_title', models.BooleanField(default=False)),
                ('block_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('link', models.ManyToManyField(blank=True, related_name='blocks', to='content.article')),
            ],
            options={
                'ordering': ['block_order'],
            },
        ),
    ]
